[project]
name = "pydantic-ai-tutorial"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "langfuse>=4.14.3",
    "logfire>=4.40.0",
    "pydantic-ai-harness[codemode]>=0.21.0",
    "pydantic-ai-slim[openai,spec,web]>=2.27.1",
    "pydantic-evals>=2.31.0",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
]
